{
  "formatVersion": "1.1",
  "component": {
    "group": "org.joml",
    "module": "joml",
    "version": "1.10.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "joml-1.10.7.jar",
          "url": "joml-1.10.7.jar",
          "size": 778679,
          "sha512": "0c2fd7ee587255223ce3bddcbaca9a3c3e2a0904fea5055977ca660c9781fb4a07880d0620ec90073b45ea720aa32337932aeb972fc8c9bee687882cb22374d5",
          "sha256": "7adf695452b2f9e63cb13bf10ca61cd3fb0dc891a61d7f846fbbf5ab4728cac6",
          "sha1": "f8c3f2e7db281bde099342dd36133de4bbba390c",
          "md5": "406299660419b6371358d30c3a2694b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "joml-1.10.7.jar",
          "url": "joml-1.10.7.jar",
          "size": 778679,
          "sha512": "0c2fd7ee587255223ce3bddcbaca9a3c3e2a0904fea5055977ca660c9781fb4a07880d0620ec90073b45ea720aa32337932aeb972fc8c9bee687882cb22374d5",
          "sha256": "7adf695452b2f9e63cb13bf10ca61cd3fb0dc891a61d7f846fbbf5ab4728cac6",
          "sha1": "f8c3f2e7db281bde099342dd36133de4bbba390c",
          "md5": "406299660419b6371358d30c3a2694b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "joml-1.10.7-sources.jar",
          "url": "joml-1.10.7-sources.jar",
          "size": 736157,
          "sha512": "bd0a866bdedb8fed686e19fcc293c512b0bb92d09e26e26733f18bfb43743f213931ec27f62704097c61d83dd4d843fecab0601e9d2b0e965184bc7cc5d57cb7",
          "sha256": "892ec906b3fd5a31cede9f25c895d69eebcc0182e1a32c58e9195a5d8e11c385",
          "sha1": "de7e11ac842f6b71d67586892a99cdb08274a9e1",
          "md5": "3ac8254241fe96f8e95d52eeea9f2e51"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "joml-1.10.7-javadoc.jar",
          "url": "joml-1.10.7-javadoc.jar",
          "size": 1730255,
          "sha512": "a1bd7369cde2db641dbddd7702552c2b60644de865693ebb62b4e108354051ad9413c4137ed1b4fa92ef35e04c55e09674cdcb0f154091b734514e5447f84019",
          "sha256": "e135af114d1acf234325c352a633c8af36e47f8840e42ce5f0cea05c81a1ec91",
          "sha1": "4b4b77e4f50a6148d7722bd6792198eeacacab40",
          "md5": "369f9ebab5080d7a7ce7ac421bd47bed"
        }
      ]
    }
  ]
}
